import test from 'node:test';import assert from 'node:assert/strict';
import {scenes,failures,sceneOrder} from '../dist/game/episode.js';
import {fresh,advance,choose,retry,replay,endingFor,validateSave,lineText,lines,factDefaults} from '../dist/game/engine.js';
import {load,save,SAVE_KEY} from '../dist/game/storage.js';
const settle=s=>{for(let n=0;n<100&&['dialogue','response'].includes(s.phase);n++)s=advance(s);return s;};
const pick=(s,id)=>settle(choose(settle(s),id));
const clone=s=>JSON.parse(JSON.stringify(s));
function route(ids=[]){let s=settle(fresh());while(s.phase!=='ending'){const choices=scenes[s.scene].choices;const id=ids.find(id=>choices.some(c=>c.id===id))||choices.find(c=>!c.failure).id;s=pick(s,id);}return s;}
test('graph has stable IDs, valid effects, ten checkpoints, eight failures, three endings',()=>{assert.equal(Object.keys(scenes).length,14);assert.equal(sceneOrder.length,14);assert.equal(new Set(sceneOrder).size,14);assert.equal(Object.values(scenes).filter(s=>s.choices).length,10);assert.equal(Object.keys(failures).length,8);const ids=new Set();for(const [id,s] of Object.entries(scenes)){assert.ok(s.lines.length);assert.ok(s.ending||s.next||s.choices);for(const c of s.choices||[]){assert.ok(!ids.has(c.id));ids.add(c.id);assert.ok(c.failure?failures[c.failure]:c.next==='ENDING'||scenes[c.next]);for(const k of Object.keys(c.effects||{}))assert.ok(k in factDefaults);if(c.failure)assert.equal(failures[c.failure].scene,id);}}});
test('every one of 512 successful choice sequences reaches correct complete ending with all clues',()=>{let paths=0;const ends=new Set(),facts=new Set();function visit(s){s=settle(s);assert.ok(validateSave(s));if(s.phase==='ending'){paths++;ends.add(s.scene);assert.equal(s.scene,endingFor(s.facts));assert.ok(s.facts.alderVisited&&s.facts.bellSeal&&s.facts.alderNote);assert.ok(s.facts.repairStyle);facts.add(JSON.stringify(s.facts));return;}for(const c of scenes[s.scene].choices.filter(c=>!c.failure))visit(choose(s,c.id));}visit(fresh());assert.equal(paths,512);assert.equal(ends.size,3);assert.equal(facts.size,32);});
test('public disclosure overrides the file; private file and private no-file differ',()=>{assert.equal(route(['C02_file','C10_truth']).scene,'E_TRUTH');assert.equal(route(['C02_file','C10_private']).scene,'E_PAPER');assert.equal(route(['C02_order','C10_private']).scene,'E_APPRENTICE');});
test('every failure restores exact pre-choice state and retains discoveries without accumulating effects',()=>{let s=settle(fresh());const seen=new Set();while(s.phase!=='ending'){for(const c of scenes[s.scene].choices.filter(c=>c.failure)){const before=clone(s);const failed=choose(s,c.id);seen.add(c.failure);assert.equal(failed.phase,'failure');assert.ok(validateSave(clone(failed)));let restored=retry(failed);assert.deepEqual(restored.facts,before.facts);assert.equal(restored.scene,before.scene);assert.equal(restored.beat,before.beat);assert.equal(restored.phase,'choice');assert.ok(restored.discoveries.failuresSeen.includes(c.failure));restored=retry(choose(restored,c.id));assert.equal(restored.discoveries.failuresSeen.filter(f=>f===c.failure).length,1);assert.deepEqual(restored.facts,before.facts);s=restored;}s=pick(s,scenes[s.scene].choices.find(c=>!c.failure).id);}assert.equal(seen.size,8);});
test('replay restores the actual saved checkpoint, not final inventory or disclosure',()=>{const final=route(['C02_file','C10_truth']);const earlier=replay(final,'S02');assert.equal(earlier.facts.hasLedgerCopy,false);assert.equal(earlier.facts.publicTruth,false);assert.equal(earlier.facts.alderNote,false);assert.ok(earlier.discoveries.endingsSeen.includes('E_TRUTH'));const later=replay(final,'S09');assert.equal(later.facts.hasLedgerCopy,true);assert.equal(later.facts.publicTruth,false);assert.ok(later.facts.alderNote);assert.throws(()=>replay(fresh(),'S10'));});
test('honest confession differs from claimed appointment; both repairs work',()=>{const honest=route(['C01_honest','C05_brace']);const bluff=route(['C01_bluff','C05_mend']);const confession=scenes.S06.lines[2];assert.match(lineText(confession,honest.facts),/let them call me/);assert.match(lineText(confession,bluff.facts),/said I was/);assert.equal(honest.facts.repairStyle,'brace');assert.equal(bluff.facts.repairStyle,'mend');});
test('save round-trips dialogue, choice, response, failure and ending; duplicate choice cannot apply twice',()=>{let s=fresh(),store=new Map();const st={getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)};const states=[s,settle(s)];s=choose(settle(s),'C01_honest');states.push(s);assert.strictEqual(choose(s,'C01_bluff'),s);s=settle(s);states.push(choose(s,'C02_stamp'));states.push(route());for(const state of states){assert.ok(save(st,state));assert.deepEqual(load(st).state,state);}});
test('corrupt/unknown saves remain untouched and storage failures never throw',()=>{for(const raw of ['{broken',JSON.stringify({...fresh(),schemaVersion:999}),JSON.stringify({...fresh(),beat:999}),JSON.stringify({...fresh(),facts:{}})]){const st={getItem:()=>raw,setItem(){throw Error('must not write')}};assert.equal(load(st).state,null);assert.ok(load(st).error);assert.equal(st.getItem(SAVE_KEY),raw);}const denied={getItem(){throw Error()},setItem(){throw Error()}};assert.ok(load(denied).error);assert.equal(save(denied,fresh()),false);});
test('new game keeps collections but resets every run fact and checkpoint',()=>{const final=route(['C02_file']);const next=fresh(final.discoveries,final.settings);assert.deepEqual(next.facts,factDefaults);assert.deepEqual(Object.keys(next.checkpoints),['S00']);assert.deepEqual(next.discoveries,final.discoveries);});
